Convert space indentation to tabs

diff --git a/gres b/gres
--- a/gres
+++ b/gres
@@ -5,7 +5,7 @@ set -e
 . functions
 
 usage() {
-    cat <<END
+	cat <<END
 Super grep, output matches captured by (PCRE) regular expression arguments.
 
 Usage:
@@ -13,7 +13,7 @@ Usage:
 
 Options:
   --whole, -w
-    Match whole input
+    Match on whole input
   --global, -g
     Enable global (multiple) matches
   --multiple-lines, -m
@@ -25,7 +25,7 @@ Options:
   --help, -h
     Display this help
 END
-    exit 2
+	exit 2
 }
 
 
@@ -39,44 +39,44 @@ sep=$'\n'
 while [[ $# -gt 0 ]]; do
 case $1 in
 --whole | -w)
-    whole=whole
-    shift
-    ;;
+	whole=whole
+	shift
+	;;
 --global | -g)
-    global=global
-    shift
-    ;;
+	global=global
+	shift
+	;;
 --multiple-line | -m)
-    multiple=multiple
-    whole=whole
-    shift
-    ;;
+	multiple=multiple
+	whole=whole
+	shift
+	;;
 --single-line | -s)
-    single=single
-    whole=whole
-    shift
-    ;;
+	single=single
+	whole=whole
+	shift
+	;;
 --ignore-case | --ignore | -i)
-    ignore=ignore
-    shift
-    ;;
+	ignore=ignore
+	shift
+	;;
 --separator | -s)
-    sep=$2
-    shift 2 || usage
-    ;;
+	sep=$2
+	shift 2 || usage
+	;;
 --help | -h)
-    usage
-    ;;
+	usage
+	;;
 --)
-    shift
-    break
-    ;;
+	shift
+	break
+	;;
 -*)
-    error "Unknown option: $1"
-    ;;
+	error "Unknown option: $1"
+	;;
 *)
-    break
-    ;;
+	break
+	;;
 esac
 done
 
@@ -94,34 +94,34 @@ tmp_file; err_file=$TMP_FILE
 err=
 
 perl -e '
-    $whole = shift;
-    $sep = shift;
+	$whole = shift;
+	$sep = shift;
 
-    @re = map { eval { qr/$_/'$mod' } or die "Invalid regex: $@" } @ARGV;
+	@re = map { eval { qr/$_/'$mod' } or die "Invalid regex: $@" } @ARGV;
 
-    sub gres {
-        for $re (@re) {
-            print $_, $sep for /$re/'$glob';
-        }
-    }
+	sub gres {
+		for $re (@re) {
+			print $_, $sep for /$re/'$glob';
+		}
+	}
 
-    if ($whole) {
-        undef $/;
+	if ($whole) {
+		undef $/;
 
-        $_ = <STDIN>;
+		$_ = <STDIN>;
 
-        gres;
-    }
-    else {
-        gres while <STDIN>;
-    }
+		gres;
+	}
+	else {
+		gres while <STDIN>;
+	}
 
 ' "$whole" "$sep" "$@" 2> "$err_file" || err=$?
 
 if [[ $err ]]; then
-    shopt -s extglob
+	shopt -s extglob
 
-    error=$(< "$err_file")
+	error=$(< "$err_file")
 
-    error "${error% at * line +([[:digit:]]).}"
+	error "${error% at * line +([[:digit:]]).}"
 fi
